[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
a_drop_app = "Fkth3sBewAfunPzzbUjGb5axoFCkPLJ3VDtgcDDuxF4H"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
